#!/usr/bin/env python3
"""Generate the e2e_test.sh script."""
import os

lines = [
    "#!/bin/bash",
    "set -euo pipefail",
    'SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"',
    'PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"',
    'FIXTURES_DIR="$PROJECT_ROOT/tests/fixtures"',
    'SCIP_ADA="$PROJECT_ROOT/bin/scip_ada"',
    'export PATH="$HOME/bin:$PATH"',
    'cd "$PROJECT_ROOT"',
    'eval "$(alr printenv 2>/dev/null)" || true',
    'PASS=0; FAIL=0; TOTAL=0',
    'for fixture in hello multi_unit generics tagged_types overloads ada2022; do',
    '  TOTAL=$((TOTAL+1))',
    '  echo "=== Testing: $fixture ==="',
    '  FD="$FIXTURES_DIR/$fixture"',
    '  GP="$(find "$FD" -maxdepth 1 -name "*.gpr" | head -1)"',
    '  if [ -z "$GP" ]; then echo "  FAIL: no gpr"; FAIL=$((FAIL+1)); continue; fi',
    '  echo "  Compiling..."',
    '  mkdir -p "$FD/obj"',
    '  if ! gprbuild -P "$GP" -q 2>&1; then echo "  FAIL: compile"; FAIL=$((FAIL+1)); continue; fi',
    '  echo "  Indexing..."',
    '  if ! "$SCIP_ADA" index --project "$GP" --output "$FD/index.scip" --exclude b__ --quiet 2>&1; then',
    '    echo "  FAIL: index"; FAIL=$((FAIL+1)); continue',
    '  fi',
    '  echo "  Generating snapshot..."',
    '  SN="$FD/snapshot_new"',
    '  rm -rf "$SN"',
    '  if ! scip snapshot --strict=false --from "$FD/index.scip" --to "$SN" 2>&1; then',
    '    echo "  FAIL: snapshot"; FAIL=$((FAIL+1)); continue',
    '  fi',
    '  SR="$FD/snapshot"',
    '  if [ -d "$SR" ]; then',
    '    echo "  Diffing..."',
    '    if [ -d "$SN/src" ] && [ -d "$SR/src" ]; then',
    '      if diff -ru "$SR/src" "$SN/src" > /dev/null 2>&1; then',
    '        echo "  PASS: matches"; PASS=$((PASS+1))',
    '      else',
    '        echo "  FAIL: differs"',
    '        diff -ru "$SR/src" "$SN/src" 2>&1 || true',
    '        FAIL=$((FAIL+1))',
    '      fi',
    '    else',
    '      echo "  PASS: no src/ to compare"; PASS=$((PASS+1))',
    '    fi',
    '  else',
    '    echo "  PASS: initial run"; PASS=$((PASS+1))',
    '  fi',
    '  rm -rf "$SN"',
    '  echo ""',
    'done',
    'echo "=================================="',
    'echo "Results: $PASS passed, $FAIL failed out of $TOTAL fixtures"',
    'if [ "$FAIL" -gt 0 ]; then exit 1; fi',
    'echo "All fixtures passed!"',
]

path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "e2e_test.sh")
with open(path, "w") as f:
    f.write("\n".join(lines) + "\n")
os.chmod(path, 0o755)
print(f"Written {path}")
